// Translation list for the EN / ខ្មែរ switch.
// Add one line per text:  ['English text', 'ខ្មែរ text'],
//  - The text must match the page exactly (spaces are ignored).
//  - Use '' on one side to hide that text in the other language
//    (for a line that only repeats the translation of the line next to it).
//  - Icon names such as bolt, arrow_forward, edit_note are not texts. Do not add them.
//  - The list is shared by all pages, so a text is translated the same way everywhere.
window.ReanRushI18n = { entries: [

  // ---- menu labels (header, bottom menu, sidebar) ----
  ['Home', 'ទំព័រដើម'],
  ['Play', 'លេង'],
  ['Games', 'ហ្គេម'],
  ['Flashcards', 'ប័ណ្ណសិក្សា'],
  ['Practice', 'ហាត់អនុវត្ត'],
  ['Progress', 'វឌ្ឍនភាព'],
  ['Game Modes', 'ប្រភេទហ្គេម'],
  ['Classes', 'ថ្នាក់រៀន'],
  ['Leaderboard', 'តារាងពិន្ទុ'],
  ['Mistake Vault', 'ឃ្លាំងកំហុស'],
  ['Avatar Shop', 'ហាងតួអង្គ'],
  ['Profile', 'ប្រវត្តិរូប'],
  ['Settings', 'ការកំណត់'],
  ['Blog', 'ប្លុក'],
  ['Pricing', 'តម្លៃ'],
  ['Class PIN', 'កូដថ្នាក់'],

  // ---- student/join-pin.html ----
  ['STUDENT BATTLE PORTAL', 'ច្រកចូលប្រកួតសិស្ស'],
  ['Room #402', 'បន្ទប់ #៤០២'],
  ['Ready for battle?', ''],
  ['', 'ត្រៀមខ្លួនប្រកួតហើយឬនៅ? 💥'],
  ['Enter Game PIN', 'បញ្ចូលកូដហ្គេម'],
  ['6-digit code', 'កូដ ៦ ខ្ទង់'],
  ['CLEAR', 'សម្អាត'],

  // ---- student/nickname.html ----
  ['STEP 2 OF 3', 'ជំហានទី ២ នៃ ៣'],
  ['48 Online', '៤៨ នាក់កំពុងអនឡាញ'],
  ['Battle Nickname', 'ឈ្មោះហៅក្រៅសម្រាប់ប្រកួត'],
  ['Pick a daring tag to represent you on the live stadium leaderboard!', 'ជ្រើសរើសឈ្មោះដ៏ក្លាហានមួយ ដើម្បីតំណាងអ្នកនៅលើតារាងពិន្ទុផ្ទាល់!'],
  ['Projector Safe: Kept friendly & visible to CADT arena screen.', 'សុវត្ថិភាពលើអេក្រង់ប្រូជេកទ័រ៖ ឈ្មោះសមរម្យ និងអាចបង្ហាញលើអេក្រង់សង្វៀន CADT។'],
  ['Your champion during the lightning rounds', 'អ្នកចំបាំងរបស់អ្នកក្នុងជុំល្បឿនលឿន'],
  ['LVL 1 ROOKIE', 'កម្រិត ១ អ្នកថ្មី'],
  ['ACTIVE', 'កំពុងប្រើ'],
  ['CONTINUE TO TEAM SELECT', 'បន្តទៅជ្រើសរើសក្រុម'],
  ['Re-enter Room PIN', 'បញ្ចូលកូដបន្ទប់ម្ដងទៀត'],

  // ---- student/home.html ----
  ['LVL 14 Battle Scout', 'កម្រិត ១៤ អ្នកស៊ើបការណ៍ប្រយុទ្ធ'],
  ['Next level', 'កម្រិតបន្ទាប់'],
  ['+660 XP to LVL 15', '+660 XP ដល់ LVL 15'],
  ['Daily Rush: 5 Questions', 'ការប្រណាំងប្រចាំថ្ងៃ៖ សំណួរ ៥'],
  ['Quick BACII warm-up •', 'ហាត់កំដៅរហ័សសម្រាប់ BACII •'],
  ['+150 XP bonus', 'រង្វាន់បន្ថែម +150 XP'],
  ['today!', 'ថ្ងៃនេះ!'],
  ['Physics: Thermodynamics & Electric Fields', 'រូបវិទ្យា៖ ទែម៉ូឌីណាមិច និងដែនអគ្គិសនី'],
  ['HOT!', 'ពេញនិយម!'],
  ['7 Days!', '៧ ថ្ងៃ!'],
  ['7-day streak', '៧ ថ្ងៃជាប់គ្នា'],
  ['5 more days to Double XP Shield!', 'នៅសល់ ៥ ថ្ងៃទៀត ដើម្បីទទួលបានខែល XP ទ្វេដង!'],
  ['LVL 3', 'កម្រិត ៣'],
  ['Baby Elephant', 'កូនដំរី'],
  ['85% Happy', 'សប្បាយចិត្ត ៨៥%'],
  ['Fed Today!', 'បានចិញ្ចឹមថ្ងៃនេះ!'],
  ['View All', 'មើលទាំងអស់'],
  ['42 DUE', 'ដល់ពេលរំលឹក ៤២'],
  ['Review cards', 'កាតរំលឹក'],
  ['SOLO', 'តែម្នាក់ឯង'],
  ['Solo practice', 'អនុវត្តតែឯង'],
  ['12 TRAPS', 'អន្ទាក់ ១២'],
  ['Mistakes', 'កំហុស'],
  ['Mistakes to fix', 'កំហុសត្រូវកែ'],
  ['LIVE', 'ផ្ទាល់'],
  ['Join class', 'ចូលថ្នាក់រៀន'],
  ['Grade 12 Battle Arena', 'សង្វៀនប្រកួតថ្នាក់ទី ១២'],
  ['3,420 students competing live', 'សិស្ស ៣,៤២០ នាក់កំពុងប្រកួតផ្ទាល់'],
  ['SPECTATE', 'មើលការប្រកួត'],
  ['ReanRush • AUB & CADT Student Project', 'ReanRush • គម្រោងសិស្ស AUB និង CADT'],
  ['Powered by High School Gamification Labs • Sponsored by ACLEDA Bank', 'ដំណើរការដោយ High School Gamification Labs • ឧបត្ថម្ភដោយធនាគារ ACLEDA'],

  // ---- student/team.html ----
  ['28/35 IN LOBBY', 'នៅក្នុងបន្ទប់រង់ចាំ ២៨/៣៥'],
  ['STAGE 03 • FINAL SQUAD SELECTION', 'ដំណាក់កាលទី ០៣ • ជ្រើសរើសក្រុមចុងក្រោយ'],
  ['CHOOSE YOUR SQUAD', 'ជ្រើសរើសក្រុមរបស់អ្នក'],
  ['SQUAD 01 : TEAM A', 'ក្រុមទី ០១ : ក្រុម A'],
  ['92% READY', 'ត្រៀមរួចរាល់ ៩២%'],
  ['Roster Status', 'ស្ថានភាពបញ្ជីសមាជិក'],
  ['14 / 16 PLAYERS', 'អ្នកលេង ១៤ / ១៦'],
  ['+11 more', '+១១ នាក់ទៀត'],
  ['SQUAD CLASH', 'ការប៉ះទង្គិចរវាងក្រុម'],
  ['SQUAD 02 : TEAM B', 'ក្រុមទី ០២ : ក្រុម B'],
  ['94% READY', 'ត្រៀមរួចរាល់ ៩៤%'],
  ['Prevents stacked teams for fair scoring', 'ការពារការប្រមូលអ្នកខ្លាំងៗក្នុងក្រុមតែមួយ ដើម្បីឱ្យពិន្ទុយុត្តិធម៌'],
  ["I'M READY TO BATTLE!", 'ខ្ញុំត្រៀមខ្លួនប្រកួតហើយ!'],
  ['RUSHY INTEL', 'ព័ត៌មានពី RUSHY'],

  // ---- student/lobby.html ----
  ['PIN', 'កូដ PIN'],
  ['34 Players', 'អ្នកលេង ៣៤ នាក់'],
  ['LIVE READY', 'ត្រៀមផ្ទាល់រួចរាល់'],
  ['Ta Prohm Arena • BACII MoEYS', 'សង្វៀនតាព្រហ្ម • BACII MoEYS'],
  ['16 Qs', 'សំណួរ ១៦'],
  ['HOST LIVE', 'គ្រូកំពុងផ្សាយផ្ទាល់'],
  ['Lokkru Vichea is previewing Question 1 on the projector! Warm up your brain cells! 🧠⚡', ''],
  ['', 'លោកគ្រូវិចិត្រកំពុងបើកផ្ទាំងបញ្ចាំងសំណួរទី ១!'],
  ['Your Squad: Team A', 'ក្រុមរបស់អ្នក៖ ក្រុម A'],
  ['18/20 Pls', 'អ្នកលេង ១៨/២០'],
  ['+13 more', '+១៣ នាក់ទៀត'],
  ['x24 Hypes', 'ការលើកទឹកចិត្ត ×២៤'],
  ['Waiting for Host...', ''],
  ['', 'កំពុងរង់ចាំលោកគ្រូចាប់ផ្តើមការប្រកួត...'],
  ['Pro Tip:', 'គន្លឹះ៖'],
  ['Fast answers earn up to 1,000 streak points in Bayon Round!', 'ឆ្លើយលឿនទទួលបានពិន្ទុជាប់គ្នារហូតដល់ ១,០០០ ក្នុងជុំបាយ័ន!'],

  // ---- student/battle.html ----
  ['BOSS RAID MODE', 'របៀបប្រយុទ្ធមេបិសាច'],
  ['Stage 3: Angkor Temple Arena', 'ដំណាក់កាលទី ៣៖ សង្វៀនប្រាសាទអង្គរ'],
  ['of 15', 'នៃ ១៥'],
  ['ROOM PIN:', 'កូដបន្ទប់៖'],
  ['HOME', 'ក្រុមម្ចាស់ផ្ទះ'],
  ['PTS', 'ពិន្ទុ'],
  ['Health Power', 'កម្លាំងជីវិត'],
  ['85% HP', 'ជីវិត ៨៥%'],
  ['80% HP', 'ជីវិត ៨០%'],
  ['HURRY!', 'ប្រញាប់!'],
  ['CHALLENGER', 'អ្នកប្រឆាំង'],
  ['NEWTONIAN LAWS', 'ច្បាប់ញូតុន'],
  ['Standard Formula Verification', 'ការផ្ទៀងផ្ទាត់រូបមន្តស្តង់ដារ'],
  ['2.5X RUSH MULTIPLIER', 'មេគុណប្រណាំង ២.៥ ដង'],
  ['CHOICE A', 'ជម្រើស A'],
  ['CHOICE B', 'ជម្រើស B'],
  ['CHOICE C', 'ជម្រើស C'],
  ['CHOICE D', 'ជម្រើស D'],
  ['POPULAR PICK', 'ជម្រើសពេញនិយម'],
  ['38 / 42 Students Answered', 'សិស្សបានឆ្លើយ ៣៨ / ៤២ នាក់'],
  ['SFX ON', 'សំឡេងបែបផែន៖ បើក'],
  ['Pause Clock', 'ផ្អាកនាឡិកា'],
  ['Projector View', 'ទិដ្ឋភាពប្រូជេកទ័រ'],
  ['PERFECT STRIKE!', 'វាយត្រូវគោលដៅល្អឥតខ្ចោះ!'],

  // ---- student/answer-result.html ----
  ['Grade 12 Physics (BACII Prep)', 'រូបវិទ្យាថ្នាក់ទី ១២ (រៀបចំ BACII)'],
  ['Ta Prohm Round', 'ជុំតាព្រហ្ម'],
  ['Phase', 'ដំណាក់កាល'],
  ['Question 07 / 16', 'សំណួរទី ០៧ / ១៦'],
  ['Result review time', 'រយៈពេលបង្ហាញលទ្ធផល (Result Review)'],
  ['Next in', 'បន្ទាប់ក្នុងរយៈពេល'],
  ['Pause', 'ផ្អាក'],
  ['Flawless Reaction!', 'ប្រតិកម្មឥតខ្ចោះ!'],
  ['CORRECT!', 'ត្រឹមត្រូវ!'],
  ['Speed:', 'ល្បឿន៖'],
  ['(Top 5% in class)', '(កំពូល ៥% ក្នុងថ្នាក់)'],
  ['🔥 4 IN A ROW!', '🔥 ត្រូវ ៤ ជាប់គ្នា!'],
  ['x1.5 BOOST', 'បង្កើនពិន្ទុ ×១.៥'],
  ['Question Review', 'ពិនិត្យសំណួរ'],
  ["Rushy's Quick Hack", 'គន្លឹះរហ័សរបស់ Rushy'],
  ["Rushy's memory tip", 'គន្លឹះចងចាំរបស់ Rushy'],
  ['Formula Sheet', 'តារាងរូបមន្ត'],
  ['ACLEDA Academic Reward Pool', 'ទុនរង្វាន់សិក្សា ACLEDA'],
  ['Current match pool:', 'ទុនរង្វាន់ប្រកួតបច្ចុប្បន្ន៖'],
  ['$150 Micro-Scholarship', 'អាហារូបករណ៍ខ្នាតតូច $១៥០'],
  ['unlocked at 80% class accuracy!', 'បើកដោយភាពត្រឹមត្រូវថ្នាក់ ៨០%!'],

  // ---- student/leaderboard.html ----
  ['Physics & Electromagnetism • BACII Grade 12', 'រូបវិទ្យា និងអេឡិចត្រូម៉ាញ៉េទិច • BACII ថ្នាក់ទី ១២'],
  ['15/15 Questions Completed', 'បានបញ្ចប់សំណួរ ១៥/១៥'],
  ['MATCH COMPLETED #RR-9042', 'ការប្រកួតបានបញ្ចប់ #RR-9042'],
  ['VICTORY FOR TEAM A!', ''],
  ['', 'ជ័យជម្នះបានទៅលើក្រុម A (Bak Touk Tigers)!'],
  ['Leader', 'អ្នកនាំមុខ'],
  ['Points Lead', 'ពិន្ទុនាំមុខ'],
  ['14 PLAYERS', 'អ្នកលេង ១៤ នាក់'],
  ['TEAM A', 'ក្រុម A'],
  ['TEAM B', 'ក្រុម B'],
  ['Team Accuracy 86%', 'ភាពត្រឹមត្រូវរបស់ក្រុម ៨៦%'],
  ['Team Accuracy 82%', 'ភាពត្រឹមត្រូវរបស់ក្រុម ៨២%'],
  ['Avg Response: 2.1s', 'ឆ្លើយតបជាមធ្យម៖ ២.១ វិនាទី'],
  ['Avg Response: 2.3s', 'ឆ្លើយតបជាមធ្យម៖ ២.៣ វិនាទី'],
  ['5x 🔥 Streak', 'ជាប់គ្នា ៥ដង 🔥'],
  ['4x ⚡ Streak', 'ជាប់គ្នា ៤ដង ⚡'],
  ['93% Acc', 'ត្រឹមត្រូវ ៩៣%'],
  ['87% Acc', 'ត្រឹមត្រូវ ៨៧%'],
  ['80% Acc', 'ត្រឹមត្រូវ ៨០%'],
  ['73% Acc', 'ត្រឹមត្រូវ ៧៣%'],
  ['67% Acc', 'ត្រឹមត្រូវ ៦៧%'],
  ['60% Acc', 'ត្រឹមត្រូវ ៦០%'],
  ['+8 More Tigers (Scores: 720 - 410 pts)', '+ខ្លាទៀត ៨ ក្បាល (ពិន្ទុ ៧២០ - ៤១០)'],
  ['+8 More Rhinos (Scores: 710 - 380 pts)', '+ក្របីទៀត ៨ ក្បាល (ពិន្ទុ ៧១០ - ៣៨០)'],
  ['POINTS ACCUMULATED', 'ពិន្ទុសរុប'],
  ['DUEL', 'ការប្រកួតទល់មុខ'],
  ['DELTA MARGIN', 'ភាពខុសគ្នាពិន្ទុ'],
  ['Round 15 / 15', 'ជុំទី ១៥ / ១៥'],
  ['Good try, rush again!', ''],
  ['', '• ការខិតខំប្រឹងប្រែងដ៏អស្ចារ្យ! សាកល្បងម្តងទៀត!'],
  ['SQUAD ACE', 'ផ្កាយក្រុម'],
  ['Classroom Projector Insights', 'ការវិភាគសម្រាប់អេក្រង់ថ្នាក់រៀន'],
  ['Technical match summary', 'សេចក្តីសង្ខេបបច្ចេកទេសការប្រកួត'],
  ['Class Accuracy', 'ភាពត្រឹមត្រូវរបស់ថ្នាក់'],
  ['78% Solid', '៧៨% ល្អ'],
  ['Hardest Question', 'សំណួរពិបាកបំផុត'],
  ['Solenoid Field (Q8)', 'ដែនសូឡេណូអ៊ីត (សំណួរ ៨)'],
  ['Fastest Answer', 'ចម្លើយលឿនបំផុត'],
  ['1.4s (Sokha)', '១.៤ វិនាទី (សុខា)'],
  ['Revenge Round', 'ជុំសងសឹក'],
  ['Revenge match (harder deck)', 'ប្រកួតសងសឹក (Harder Deck)'],
  ['Play Again', 'លេងម្តងទៀត'],
  ['Restart', 'លេងម្តងទៀត (Restart)'],
  ['Share Winner Certificate', 'ចែករំលែកវិញ្ញាបនបត្រអ្នកឈ្នះ']

] };